src/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.SnippetAPIView.as_view()),
    path('snippet/<uuid:pk>', views.SnippetAPIView.as_view())
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

# from api import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html')),
    path('', include('sharing_code.urls')),
    path('api/v1/', include('api.urls'))
]

src/sharing_code/urls.py
from django.urls import path
from . import views
from .decorators import check_recaptcha

urlpatterns = [
    path('create', check_recaptcha(views.CreateSnippet.as_view()), name='create'),
    path('snippet/<uuid:pk>', views.ViewSnippet.as_view(), name='detail'),
]

app_name = 'snippet'

src/api/models.py
from django.db import models

# Create your models here.

src/sharing_code/models.py
from django.db import models
from django.shortcuts import reverse
import uuid


class Snippet(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=50)
    code = models.TextField()
    langs = [('Text', 'None'),
             ('Python', 'Python'),
             ('JavaScript', 'Javascript'),
             ]
    lang = models.CharField(max_length=18, choices=langs, default='Text')
    date = models.DateTimeField(auto_now_add=True)

    class Meta():
        db_table = "Snippets"
        verbose_name = "Snippet"
        verbose_name_plural = "Snippets"

    def __str__(self):
        return self.id.hex

src/sharing_code/forms.py
from django import forms
from .models import Snippet
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, ButtonHolder, Field, Div, HTML


class SnippetForm(forms.ModelForm):
    helper = FormHelper()

    class Meta():
        model = Snippet
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Snippet title'}),
            'code': forms.Textarea(attrs={'placeholder': 'Your snippet code'}),
        }
        fields = {'title', 'code', 'lang'}
        labels = {
            'title': '',
            'code': '',
            'lang': '',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                Field('title', css_class='focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent', ),
                Field('code', css_class='focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent'),
                Field('lang', css_class='focus:ring-2 focus:ring-indigo-500'),
                Div(
                    HTML(
                        '<div class="g-recaptcha" data-sitekey="6LfzZlAaAAAAANHl7mevl6PaGUzu1S9YquYL77jX"></div>'),
                    Submit('submit', 'Submit', css_class='w-full py-6 border-2 bg-white border-indigo-500 text-indigo-500 font-bold rounded-md transition duration-300 ease-in-out hover:bg-indigo-500  hover:text-white'),
                    css_class='flex items-center buttons'
                )
                ,
                css_class='rounded-3xl mx-auto w-10/12 flex flex-col text-gray-800 border border-gray-300 p-4 shadow-lg max-w-2xl'
            )
        )

src/api/views.py
from rest_framework.response import Response
from rest_framework.views import APIView

from sharing_code.models import Snippet
from .serializers import SnippetSerializer


class SnippetAPIView(APIView):

    def get(self, request, *args, **kwargs):
        if 'pk' in kwargs:
            return self.retrieve(request, *args, **kwargs)
        else:
            return self.list(request, *args, **kwargs)

    def retrieve(self, request, *args, **kwargs):
        snippet = Snippet.objects.get(pk=kwargs['pk'])
        serializer = SnippetSerializer(instance=snippet)
        return Response(serializer.data)

    def list(self, request, *args, **kwargs):
        queryset = Snippet.objects.all()
        serializer = SnippetSerializer(queryset, many=True)
        return Response(serializer.data)

src/sharing_code/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from .forms import SnippetForm
from .models import Snippet
from django.views.generic import DetailView, FormView


class CreateSnippet(FormView):
    form_class = SnippetForm
    template_name = 'createSnippet.html'

    def form_valid(self, form):
        if self.request.recaptcha_is_valid:
            snippet = form.save(commit=False)
            snippet.save()
            return HttpResponseRedirect(reverse('snippet:detail', kwargs={'pk': snippet.id}), self.get_context_data())
        return render(self.request, 'createSnippet.html', self.get_context_data())


class ViewSnippet(DetailView):
    model = Snippet
    context_object_name = 'snippet'
    template_name = 'viewSnippet.html'

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}{% endblock title %}</title>
    <link rel="shortcut icon" href="{% static 'img/fav.png' %}" type="image/x-icon">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    {% block extra_head %} {% endblock extra_head %}
</head>
<body>

    {% block body %}{% endblock body %}

    {% block extra_body %}{% endblock extra_body %}
</body>
</html>

src/templates/createSnippet.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}

{% block title%}create Snippet{% endblock title %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}" />

    <script type="text/javascript" src={% static 'js/code.js' %}></script>
{% endblock extra_head %}

{% block body %}
<div class="mx-auto pt-12">
    <h1 class="text-center text-indigo-500 text-5xl font-bold mb-4">Write your snippet to share</h1>
    <form method="post" class="uniForm">
        {% csrf_token %}
        <!--{{ form.title|as_crispy_field }}
        {{ form.code|as_crispy_field }}
        {{ form.lang|as_crispy_field }}
        <div class="form-group g-recaptcha" data-sitekey="6LfzZlAaAAAAANHl7mevl6PaGUzu1S9YquYL77jX"></div>-->
        {% crispy form %}
        <script src='https://www.google.com/recaptcha/api.js'></script>

    </form>
</div>
{% endblock body %}

{% block extra_body %}{% endblock extra_body %}

src/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title%}CodeShare{% endblock title %}

{% block extra_head %}{% endblock extra_head %}

{% block body %}
<div class="home py-24 font-bold text-center">
    <h1 class="text-5xl mb-5">Hello there&#128075;</h1>
    <p class="text-3xl mb-5">Here you can create snippets of code and share them with the world&#127757;</p>
    <p class="text-xl mb-12">&#9888; After 10 days snippets are deleted</p>
    <a class="tryit px-10 py-2 bg-indigo-500 text-white text-xl font-bold  rounded-3xl" href="{% url 'snippet:create' %}">Try it!</a>
</div>

{% endblock body %}

{% block extra_body %}{% endblock extra_body %}

src/templates/viewSnippet.html
{% extends 'base.html' %}

{% load static %}

{% block title%}{{snippet.title}}{% endblock title %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/view.css' %}">
{% endblock extra_head %}

{% block body %}
<div class="mx-auto mt-12 rounded-3xl w-10/12 flex flex-col text-gray-800 border border-gray-300 p-4 shadow-lg max-w-7xl">

    <div class="title">
        <h1 class="text-center text-indigo-500 text-5xl font-bold mb-3 mx-auto">{{snippet.title}}</h1>
        {% if snippet.lang == 'Python' %}
        <img src="{% static 'img/python.svg'%}" alt="py" height="40px" width="40px">
        {% elif snippet.lang == 'JavaScript'%}
        <img src="{% static 'img/javascript.svg'%}" alt="js" height="40px" width="40px">
        {% endif %}
    </div>

    <div class="copy-link mb-4">
        <input value="{{request.get_full_path}}" id="link" readonly class="border-2 border-indigo-500 rounded-md">
        <button class="px-2 py-1 text-white bg-indigo-500 font-bold rounded-md" onclick="Copy()">Copy</button>
    </div>

    <div class="code rounded-3xl border border-gray-300 mb-4 flex-wrap">
        <pre><code>
            {{snippet.code}}
        </code></pre>
    </div>

</div>


{% endblock body %}

{% block extra_body %}
    <script src={% static 'js/copy.js' %} ></script>
{% endblock extra_body %}